---
github_actions:
    - ".github/**"
dev_container:
    - ".devcontainer/**"
configuration:
    - ".*"
    - "*.js"
    - "*.json"
    - "*.toml"
    - "*.yaml"
    - "*.yml"
build:
    - "Gruntfile.js"
    - "scripts/**"
documentation:
    - "*.md"
    - LICENSE
site:
    - "site/**"
    - "_config*"
dependencies:
    - "*.lock"
