---
# This is the pre-commit config for CI workflows. It bypasses the local
# pre-commit hooks.

# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: v4.0.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: .devcontainer/|.vscode/|tests/|feed\.json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        types: [python]
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, production]

  - repo: "https://github.com/crate-ci/typos"
    rev: typos-dict-v0.11.37
    hooks:
      - id: typos

  - repo: "https://github.com/djlint/djLint"
    rev: v1.36.1
    hooks:
      - id: djlint
        args: ["--configuration", "pyproject.toml"]

  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: ^.*\.(yaml|yml)$
        entry: yamllint --strict --config-file .yamllint.yml
