[default]
    default.locale = "en_us"

    [default.extend-words]
        Froms      = "Froms"      # Apple property key "kMDItemWhereFroms"
        Pn         = "Pn"         # flag used in script "-Pn"
        layou      = "layou"
        natelandau = "natelandau"
        nd         = "nd"

[files]
    extend-exclude = ["*.json", "*_cache", ".venv", "cache"]
