---
environment: prod
baseurl: "https://staging.natelandau.com"
analyticsID: UA-80560-6
disqusShortName: natelandaudev
destination: ./_siteStage
include-js: true
giscus_data_category_id: DIC_kwDOIM6z9s4CSAJf
giscus_data_category: staging-comments
