---
environment: stage
production_url: "https://staging.natelandau.com"
baseurl: "https://localhost:8888"
host: localhost
port: 8888
analyticsID: UA-80560-6
disqusShortName: natelandaudev
destination: ./_siteStage
include-js: true
