---
environment: prod
production_url: "https://staging.natelandau.com"
baseurl: "https://staging.natelandau.com"
analyticsID: UA-80560-6
disqusShortName: natelandaudev
destination: ./_siteStage
include-js: true
