---
name: "Delete files on staging"

on:
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # DEPENDENCIES
            # -----------------------------------
            - name: Checkout
              uses: actions/checkout@v4

            - name: "Delete Files from Staging S3"
              run: scripts/deploy-to-s3.sh --force --bucket-name=${{ secrets.AWS_S3_TEST_BUCKET_NAME }} --delete-all

            - name: "Create AWS Cloudfront Invalidation"
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_STAGING_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
