---
name: Pull Request Linter

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize
        branches:
            - main

permissions:
    contents: read

jobs:
    lint:
        permissions:
            pull-requests: read
            statuses: write
        runs-on: ubuntu-latest

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
              with:
                  egress-policy: block
                  allowed-endpoints: >
                      api.github.com:443

            - name: Lint Pull Request
              uses: amannn/action-semantic-pull-request@v5
              with:
                  validateSingleCommit: true
                  wip: true
                  types: |
                      fix
                      feat
                      docs
                      style
                      refactor
                      perf
                      test
                      build
                      ci
                      bump
                  requireScope: false
                  subjectPattern: ^(?![A-Z]).+$
                  subjectPatternError: |
                      The subject "{subject}" found in the pull request title "{title}"
                      didn't match the configured pattern. Please ensure that the subject
                      doesn't start with an uppercase character.
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
