---
name: "Test Builds"

on:
    pull_request:
        types: [opened, reopened]
    push:
        paths-ignore:
            - "README.md"
            - "CHANGELOG.md"
            - ".cz.yaml"
            - ".pre-commit-config.yaml"
            - ".vscode/**"
            - ".devcontainer/**"
    workflow_dispatch:

jobs:
    build_matrix:
        strategy:
            fail-fast: true
            matrix:
                task: ["build_dev", "build_stage", "build_prod", "deploy_prod", "build_stage_deploy"]
        runs-on: ubuntu-latest
        steps:
            # DEPENDENCIES
            # -----------------------------------
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Set up Ruby"
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.1"
                  bundler-cache: true

            - name: "Install gems"
              run: bundle install

            - name: "Use Node.js 16.x"
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  cache: "npm"

            - name: "Install nodejs packages"
              run: npm install

            - name: "Install apt packages"
              run: sudo apt-get install -y libxml2-utils yamllint libmagickwand-dev

            # Test Builds
            # -----------------------------------
            - name: "Build task: ${{ matrix.task }}"
              run: npx grunt ${{ matrix.task }}
